"""initial_schema

Revision ID: a3b4fcc66da6
Revises: 
Create Date: 2026-02-12 15:26:38.502782
"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a3b4fcc66da6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # pgvector 확장 활성화
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_models',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('model_id', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('input_cost_per_1m', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('output_cost_per_1m', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('max_context_length', sa.Integer(), nullable=False),
    sa.Column('is_adult_only', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'model_id', name='uq_llm_provider_model')
    )
    op.create_table('webtoons',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=True),
    sa.Column('genre', postgresql.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('age_rating', sa.String(length=20), nullable=False),
    sa.Column('total_episodes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='ongoing', nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("age_rating IN ('all', '12+', '15+', '18+')", name='ck_webtoons_age_rating'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('episodes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('webtoon_id', sa.UUID(), nullable=False),
    sa.Column('episode_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('published_at', sa.Date(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['webtoon_id'], ['webtoons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('webtoon_id', 'episode_number', name='uq_episode_webtoon_number')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('email_hash', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=20), server_default='user', nullable=False),
    sa.Column('age_group', sa.String(length=20), server_default='unverified', nullable=False),
    sa.Column('adult_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auth_method', sa.String(length=20), nullable=True),
    sa.Column('preferred_llm_model_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("age_group IN ('minor_safe', 'adult_verified', 'unverified')", name='ck_users_age_group'),
    sa.CheckConstraint("role IN ('user', 'admin')", name='ck_users_role'),
    sa.ForeignKeyConstraint(['preferred_llm_model_id'], ['llm_models.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nickname')
    )
    op.create_table('comment_stats',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('episode_id', sa.UUID(), nullable=False),
    sa.Column('total_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('positive_ratio', sa.Float(), nullable=True),
    sa.Column('negative_ratio', sa.Float(), nullable=True),
    sa.Column('top_emotions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('toxicity_score', sa.Float(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('toxicity_score BETWEEN 0 AND 1', name='ck_comment_toxicity'),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consent_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('consent_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('scope', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('granted', 'revoked')", name='ck_consent_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_consent_user', 'consent_logs', ['user_id', 'consent_type'], unique=False)
    op.create_table('episode_embeddings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('episode_id', sa.UUID(), nullable=False),
    sa.Column('chunk_type', sa.String(length=20), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('episode_emotions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('episode_id', sa.UUID(), nullable=False),
    sa.Column('emotion_label', sa.String(length=30), nullable=False),
    sa.Column('intensity', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence BETWEEN 0 AND 1', name='ck_emotion_confidence'),
    sa.CheckConstraint('intensity BETWEEN 0 AND 1', name='ck_emotion_intensity'),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('episode_id', 'emotion_label', 'model_version', name='uq_emotion_episode_label_version')
    )
    op.create_index('idx_emotions_episode', 'episode_emotions', ['episode_id'], unique=False)
    op.create_table('live2d_models',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('model_path', sa.Text(), nullable=False),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('emotion_mappings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_live2d_created_by', 'live2d_models', ['created_by'], unique=False)
    op.create_table('spoiler_settings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('webtoon_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('max_episode', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("mode IN ('off', 'theme_only', 'up_to', 'full')", name='ck_spoiler_mode'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['webtoon_id'], ['webtoons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'webtoon_id', name='uq_spoiler_user_webtoon')
    )
    op.create_table('user_memories',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('memory_type', sa.String(length=20), nullable=False),
    sa.Column('namespace', sa.String(length=50), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'namespace', 'key', name='uq_memory_user_ns_key')
    )
    op.create_table('personas',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=20), server_default='user_created', nullable=False),
    sa.Column('visibility', sa.String(length=20), server_default='private', nullable=False),
    sa.Column('moderation_status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('age_rating', sa.String(length=20), server_default='all', nullable=False),
    sa.Column('persona_key', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('style_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('safety_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('review_template', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('catchphrases', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('live2d_model_id', sa.UUID(), nullable=True),
    sa.Column('background_image_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("age_rating IN ('all', '15+', '18+')", name='ck_personas_age_rating'),
    sa.CheckConstraint("moderation_status IN ('pending', 'approved', 'blocked')", name='ck_personas_moderation'),
    sa.CheckConstraint("type IN ('system', 'user_created')", name='ck_personas_type'),
    sa.CheckConstraint("visibility IN ('private', 'public', 'unlisted')", name='ck_personas_visibility'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['live2d_model_id'], ['live2d_models.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('persona_key', 'version', name='uq_persona_key_version')
    )
    op.create_index('idx_personas_created_by', 'personas', ['created_by'], unique=False)
    op.create_index('idx_personas_moderation', 'personas', ['moderation_status'], unique=False)
    op.create_index('idx_personas_type_visibility', 'personas', ['type', 'visibility'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('persona_id', sa.UUID(), nullable=False),
    sa.Column('llm_model_id', sa.UUID(), nullable=True),
    sa.Column('webtoon_id', sa.UUID(), nullable=True),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'archived')", name='ck_session_status'),
    sa.ForeignKeyConstraint(['llm_model_id'], ['llm_models.id'], ),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['webtoon_id'], ['webtoons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sessions_user', 'chat_sessions', ['user_id', 'last_active_at'], unique=False)
    op.create_table('lorebook_entries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('persona_id', sa.UUID(), nullable=True),
    sa.Column('webtoon_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('persona_id IS NOT NULL OR webtoon_id IS NOT NULL', name='ck_lorebook_target'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['webtoon_id'], ['webtoons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lore_created_by', 'lorebook_entries', ['created_by'], unique=False)
    op.create_index('idx_lore_persona', 'lorebook_entries', ['persona_id'], unique=False)
    op.create_index('idx_lore_webtoon', 'lorebook_entries', ['webtoon_id'], unique=False)
    op.create_table('review_cache',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('episode_id', sa.UUID(), nullable=False),
    sa.Column('persona_id', sa.UUID(), nullable=False),
    sa.Column('spoiler_mode', sa.String(length=20), nullable=False),
    sa.Column('review_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('episode_id', 'persona_id', 'spoiler_mode', name='uq_review_cache')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('emotion_signal', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('policy_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('user', 'assistant', 'system')", name='ck_message_role'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_messages_session', 'chat_messages', ['session_id', 'created_at'], unique=False)
    op.create_table('token_usage_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('llm_model_id', sa.UUID(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['llm_model_id'], ['llm_models.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_usage_model', 'token_usage_logs', ['llm_model_id', 'created_at'], unique=False)
    op.create_index('idx_usage_session', 'token_usage_logs', ['session_id'], unique=False)
    op.create_index('idx_usage_user', 'token_usage_logs', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_usage_user', table_name='token_usage_logs')
    op.drop_index('idx_usage_session', table_name='token_usage_logs')
    op.drop_index('idx_usage_model', table_name='token_usage_logs')
    op.drop_table('token_usage_logs')
    op.drop_index('idx_messages_session', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_table('review_cache')
    op.drop_index('idx_lore_webtoon', table_name='lorebook_entries')
    op.drop_index('idx_lore_persona', table_name='lorebook_entries')
    op.drop_index('idx_lore_created_by', table_name='lorebook_entries')
    op.drop_table('lorebook_entries')
    op.drop_index('idx_sessions_user', table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index('idx_personas_type_visibility', table_name='personas')
    op.drop_index('idx_personas_moderation', table_name='personas')
    op.drop_index('idx_personas_created_by', table_name='personas')
    op.drop_table('personas')
    op.drop_table('user_memories')
    op.drop_table('spoiler_settings')
    op.drop_index('idx_live2d_created_by', table_name='live2d_models')
    op.drop_table('live2d_models')
    op.drop_index('idx_emotions_episode', table_name='episode_emotions')
    op.drop_table('episode_emotions')
    op.drop_table('episode_embeddings')
    op.drop_index('idx_consent_user', table_name='consent_logs')
    op.drop_table('consent_logs')
    op.drop_table('comment_stats')
    op.drop_table('users')
    op.drop_table('episodes')
    op.drop_table('webtoons')
    op.drop_table('llm_models')
    # ### end Alembic commands ###
